kind = "api"
previewPath = "/"
title = "Static Site"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "Static Site"
paths = ["/"]

[services.development]
run = "node /home/runner/workspace/serve.mjs"
